### ISSUE TITLE
pywin32_version

### ISSUE THREAD

**Issue by Kerber0ss** [IlyaKukharchuk/BlumClicker#1]
При установке зависимостей на mac m1 sonoma вываливается с ошибкой

`File "/private/var/folders/08/s979fjw972n3q9qhdbv35rtm0000gn/T/pip-build-env-t4cpptzv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/08/s979fjw972n3q9qhdbv35rtm0000gn/T/pip-build-env-t4cpptzv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/08/s979fjw972n3q9qhdbv35rtm0000gn/T/pip-build-env-t4cpptzv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.`

**Comment by SerhiiL06** [comment]
piwin32 предназначен только для работы на windows. Потому надо переписывать код для работы на Mac/Linux

**Comment by Kerber0ss** [comment]
Название либы намекает) 
Но, в описании проекта есть шаги по активации venv для разных ос, видимо с намеком что там тоже должно работать? Поэтому или либу менять или описание, ждем коммент автора.

**Comment by IlyaKukharchuk** [comment]
Текущие библиотеки софта работают только с windows. За версию под Mac браться нет мотивации, хотя случайные спонсоры могут поменять ситуацию)) 🫣
