### ISSUE TITLE
pyscreeze

### ISSUE THREAD

**Issue by Kerber0ss** [IlyaKukharchuk/BlumClicker#2]
При указании кнопки старта когда игра закончилась получаем ошибку и кнопка не прожимается.
В самой игре все кликается и работает. 

Python 3.12.6 , Windows 11.
 ```
 File "C:\Users\test\Downloads\BlumClicker-main\BlumClicker-main\clicker_by_crypto_groove.py", line 224, in check_and_click_point
    color = pyautogui.screenshot().getpixel((x, y))
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\Downloads\BlumClicker-main\BlumClicker-main\venv\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
```

**Comment by IlyaKukharchuk** [comment]
Не могу воспроизвести проблему, у меня кнопка старта между играми нажимается без проблем и ошибок.

**Comment by Kerber0ss** [comment]
> Не могу воспроизвести проблему, у меня кнопка старта между играми нажимается без проблем и ошибок.
Python тоже 3.12.6 ?

могу увидеть pip list?

**Comment by IlyaKukharchuk** [comment]
Python 3.10.10

pip list:
Package                      Version
---------------------------- -----------
aiofiles                     23.1.0     
aiogram                      2.25.1     
aiohttp                      3.8.4      
aiosignal                    1.3.1      
altgraph                     0.17.4     
anyio                        4.3.0      
astroid                      3.2.2      
asttokens                    2.4.1      
async-timeout                4.0.3      
attrs                        23.2.0     
Babel                        2.9.1      
beautifulsoup4               4.12.3     
Brotli                       1.1.0      
cachetools                   5.3.3      
certifi                      2022.12.7  
cffi                         1.16.0     
charset-normalizer           3.1.0      
click                        8.1.7      
colorama                     0.4.6      
colorlog                     6.8.2      
comm                         0.2.2      
contourpy                    1.2.1      
cryptography                 42.0.5     
cycler                       0.12.1     
debugpy                      1.8.1      
decompyle3                   3.9.1      
decorator                    4.4.2      
dill                         0.3.8      
distlib                      0.3.8      
distro                       1.9.0      
dnspython                    2.6.1      
et-xmlfile                   1.1.0      
exceptiongroup               1.2.0      
executing                    2.0.1
fake-useragent               1.5.1
filelock                     3.15.4
fonttools                    4.51.0
frozenlist                   1.3.3
google-ai-generativelanguage 0.6.2
google-api-core              2.17.1
google-api-python-client     2.86.0
google-auth                  2.28.1
google-auth-httplib2         0.2.0
google-generativeai          0.5.2
googleapis-common-protos     1.62.0
graphviz                     0.20.3
greenlet                     3.0.3
grpcio                       1.62.2
grpcio-status                1.62.2
h11                          0.14.0
h2                           4.1.0
hpack                        4.0.0
httpcore                     1.0.5
httplib2                     0.22.0
httpx                        0.27.0
hyperframe                   6.0.1
idna                         3.4
imageio                      2.34.0
imageio-ffmpeg               0.4.9
iniconfig                    2.0.0
instagrapi                   1.19.7
ipykernel                    6.29.4
ipython                      8.25.0
isort                        5.13.2
jedi                         0.19.1
jupyter_client               8.6.2
jupyter_core                 5.7.2
keyboard                     0.13.5
kiwisolver                   1.4.5
llvmlite                     0.42.0
lxml                         5.2.2
magic-filter                 1.0.9
markdown-it-py               3.0.0
matplotlib                   3.9.0
matplotlib-inline            0.1.7
mccabe                       0.7.0
mdurl                        0.1.2
MIDIUtil                     1.2.1
MouseInfo                    0.1.3
moviepy                      1.0.3
mss                          9.0.1
multidict                    6.0.4
mutagen                      1.47.0
mysql-connector-python       8.0.33
nest-asyncio                 1.6.0
numba                        0.59.1
numpy                        1.26.4
openai                       1.28.0
opencv-python                4.9.0.80
openpyxl                     3.1.3
outcome                      1.3.0.post0
packaging                    24.0
pandas                       2.2.2
parso                        0.8.4
pathlib2                     2.3.7.post1
pefile                       2023.2.7
pillow                       10.2.0
pip                          24.1.1
platformdirs                 4.2.2
pluggy                       1.4.0
proglog                      0.1.10
prompt_toolkit               3.0.46
proto-plus                   1.23.0
protobuf                     4.25.3
psutil                       5.9.8
psycopg2                     2.9.9
pure-eval                    0.2.2
pyasn1                       0.5.1
pyasn1-modules               0.3.0
PyAutoGUI                    0.9.54
pycparser                    2.21
pycryptodome                 3.20.0
pycryptodomex                3.18.0
pydantic                     1.10.9
pydumpck                     1.20.1
pygame                       2.2.0
PyGetWindow                  0.0.9
Pygments                     2.17.2
pyinstaller                  6.7.0
pyinstaller-hooks-contrib    2024.6
PyJWT                        2.8.0
pylint                       3.2.3
pymongo                      4.7.2
PyMsgBox                     1.0.9
pynput                       1.7.7
pyparsing                    3.1.1
pyperclip                    1.8.2
pypiwin32                    223
PyQt5                        5.15.10
PyQt5-Qt5                    5.15.2
PyQt5-sip                    12.13.0
PyRect                       0.2.0
PyScreeze                    0.1.30
PySocks                      1.7.1
pytest                       8.1.1
pytest-asyncio               0.23.7
python-dateutil              2.9.0.post0
python-dotenv                0.21.1
python-telegram-bot          12.8
pythondialog                 3.5.3
pytweening                   1.2.0
pytz                         2022.7.1
pywin32                      306
pywin32-ctypes               0.2.2
pyzmq                        26.0.3
random2                      1.0.2
redis                        5.0.4
requests                     2.31.0
rich                         13.5.2
schedule                     1.2.2
scidatetime                  1.20.2
selenium                     4.19.0
setuptools                   65.5.0
sgtpyutils                   1.20.1
six                          1.16.0
sniffio                      1.3.1
sortedcontainers             2.4.0
soupsieve                    2.5
spark-parser                 1.8.9
SQLAlchemy                   2.0.9
stack-data                   0.6.3
term-background              1.0.1
tinyaes                      1.1.0
tomli                        2.0.1
tomlkit                      0.12.5
tornado                      6.4
tqdm                         4.66.2
traitlets                    5.14.3
trio                         0.25.0
trio-websocket               0.11.1
typing_extensions            4.11.0
tzdata                       2024.1
uncompyle6                   3.9.1
uritemplate                  4.1.1
urllib3                      2.2.1
virtualenv                   20.26.3
wcwidth                      0.2.13
webdriver-manager            4.0.1
websockets                   12.0
wsproto                      1.2.0
xdis                         6.1.0
yarl                         1.8.2
yt-dlp                       2023.11.14

**Comment by Kerber0ss** [comment]
Во, спасибо, теперь все работает!
