### ISSUE TITLE
Ловит бомбы каждую вторую игру...

### ISSUE THREAD

**Issue by fememystic** [IlyaKukharchuk/BlumClicker#5]

**Comment by IlyaKukharchuk** [comment]
попробуй убрать задержку, если не устраивает результат 
`time.sleep(random.uniform(0.01, 0.03))  # Случайная задержка между кликами (можно закомментировать эту строку, если хотите минимизировать клики по бомбам и собирать максимальное количество очков)
`

**Comment by IlyaKukharchuk** [comment]
но вероятнее всего, что ты выбираешь слишком большую область, а не тонкий прямоугольник, как рекомендовано.
