### ISSUE TITLE
Как редактировать код, чтобы кликер нажимал и на белые пиксели

### ISSUE THREAD

**Issue by MorinCerber** [IlyaKukharchuk/BlumClicker#6]
Заранее благодарю

**Comment by IlyaKukharchuk** [comment]
а есть смысл?

**Comment by MorinCerber** [comment]
> а есть смысл?
> 
> 

Есть, в понедельник ожидается мемпад с токеном DOGS, планирую их собирать в том числе)

**Comment by IlyaKukharchuk** [comment]
Если будет обнова, я скрипт адаптирую под нее и выложу

**Comment by danazor** [comment]
> If it is updated, I will adapt the script for it and post it

they re announced earn $dogs in games bro. So lets cook

**Comment by Rvia43533** [comment]
> Если будет обнова, я скрипт адаптирую под нее и выложу

Приветствую, Можем мы ожидать обновы?

**Comment by IlyaKukharchuk** [comment]
There are no dogs in the game. Or maybe they appear rarely?
![image](https://github.com/user-attachments/assets/0f885f6c-ac83-4839-a655-46e5a7e2e31c)

**Comment by Rvia43533** [comment]
> There are no dogs in the game. Or maybe they appear rarely? ![image](https://private-user-images.githubusercontent.com/63457388/377563040-0f885f6c-ac83-4839-a655-46e5a7e2e31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDc5NTYsIm5iZiI6MTcyOTI0NzY1NiwicGF0aCI6Ii82MzQ1NzM4OC8zNzc1NjMwNDAtMGY4ODVmNmMtYWM4My00ODM5LWE2NTUtNDZlNWE3ZTJlMzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDEwMzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YWM3NGJlY2U2ODk5MTUxODVlNzk4YWU1ZjQxMTQ0Y2FjYzc1OGJkMTY2ODhjNmY3NTY5NTAyMjMwOTJhZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WsEgL_Rz9eSpqqXMM_KUFGVIcPuSc25j5E6LHeJd-iA)

Видимо тебе не дали доступ. Не всем дали. 
![Screenshot_20241018_133538_org telegram messenger](https://github.com/user-attachments/assets/1f805511-2bc7-4fc4-aea2-9cd24ee7241e)

**Comment by MorinCerber** [comment]
> димо тебе не дали доступ. Не всем дали. В среднем за игру 100-1

Как добавить белую маску?
