### ISSUE TITLE
Не выбирает область

### ISSUE THREAD

**Issue by MRIntrovertos2024** [IlyaKukharchuk/BlumClicker#8]
Добрый вечер. Подскажите в чём может быть проблема. Запустил бота. Прожимаю задать область, появляется полупрозрачное окно, но выбрать область не могу не как мышкой.

**Comment by IlyaKukharchuk** [comment]
попробуй подогнать версии библиотек и питона под [мои](https://github.com/IlyaKukharchuk/BlumClicker/issues/2)
